cities = [
    {"city": "Phoenix", "state": "AZ"},
    {"city": "Flagstaff", "state": "AZ"},
    {"city": "Los Angeles", "state": "CA"},
    {"city": "Denver", "state": "CO"},
    {"city": "Naperville", "state": "IL"},
    {"city": "Boise", "state": "ID"},
    {"city": "Jersey City", "state": "NJ"},
    {"city": "New York City", "state": "NY"},
    {"city": "Charlotte", "state": "NC"},
    {"city": "Raleigh", "state": "NC"},
    {"city": "Wilmington", "state": "NC"},
    {"city": "Bellingham", "state": "WA"},
    {"city": "Seattle", "state": "WA"},
    {"city": "Dover", "state": "DE"},
    {"city": "Atlanta", "state": "GA"},
    {"city": "Greenville", "state": "SC"},
    {"city": "Myrtle Beach", "state": "SC"},
    {"city": "Sioux Falls", "state": "SD"},
    {"city": "Springfield", "state": "MO"},
    {"city": "Las Vegas", "state": "NV"},
    {"city": "Portland", "state": "ME"},
    {"city": "Austin", "state": "TX"},
    {"city": "Dallas", "state": "TX"},
    {"city": "Houston", "state": "TX"},
    {"city": "San Antonio", "state": "TX"},
    {"city": "Orlando", "state": "FL"},
    {"city": "Sarasota", "state": "FL"},
    {"city": "Tampa", "state": "FL"},
    {"city": "Salt Lake City", "state": "UT"},
    {"city": "Nashville", "state": "TN"}
]
